services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resume-frontend
    ports:
      - "3000:3000"
      - "443:443"
    depends_on:
      - resume-backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge